### ISSUE TITLE
file not found error

### ISSUE THREAD

**Issue by 23Rj20** [ExponentialML/AnimateDiff-MotionDirector#16]
![Screenshot 2024-02-14 144855](https://github.com/ExponentialML/AnimateDiff-MotionDirector/assets/160009391/6854c9af-5339-4200-be12-559f7b1fbaee)

how to correct this error

**Comment by ExponentialML** [comment]
Closing as it's unrelated to this repository. To answer your question, please try double checking your paths.

**Comment by 23Rj20** [comment]
the path is correct still it shows that error can you please check this error
https://github.com/kabachuha/sd-webui-text2video/issues/241
I have pasted the link with complete error details.
