### ISSUE TITLE
Division by zero error

### ISSUE THREAD

**Issue by BlakeOne** [ExponentialML/AnimateDiff-MotionDirector#3]
> File "/content/drive/MyDrive/AnimateDiff-MotionDirector/train.py", line 715, in main
> num_update_steps_per_epoch = math.ceil(len(train_dataloader) / gradient_accumulation_steps)
> num_train_epochs = math.ceil(max_train_steps / num_update_steps_per_epoch)
> ZeroDivisionError: division by zero
> 

I tried printing `len(train_dataloader)` and found that it's 0. So I double checked that I provided the correct video path - I'm using a single video with 16 frames, size 512 x 512, MP4/H264, FPS 8, created using the Comfy VHS Combine node.

**Comment by Cubey42** [comment]
did you figure out the issue?

**Comment by al3dv2** [comment]
Please help I have the same problem
